### ISSUE TITLE
Don't associate textual mode with visual abilities

### ISSUE THREAD

**Issue by nvdaes** [benetech/UX-Guide-EPUB-A11y-Metadata#1]
Replace: > Audiobook
Values: Yes / (if No - Omit this section)
This data is derived from the EPUB package metadata inside the OPF file:
<meta property="schema:accessModeSufficient">auditory</meta>
If this metadata exists (ie. "auditory" within accessModeSufficient by itself) then report "Audiobook: Yes".
Important: This is not the same as "textual, auditory" or "auditory, textual" as this indicates that the book requires both visual and auditory abilities to access the data, not auditory alone. 

With:
> > Audiobook
Values: Yes / (if No - Omit this section)
This data is derived from the EPUB package metadata inside the OPF file:
<meta property="schema:accessModeSufficient">auditory</meta>
If this metadata exists (ie. "auditory" within accessModeSufficient by itself) then report "Audiobook: Yes".
Important: This is not the same as "textual, auditory" or "auditory, textual" as this indicates that the book requires both textual and auditory abilities to access the data, not auditory alone.

**Comment by clapierre** [comment]
Pull request fixed this issue marking this as closed.
